In [1]:
import numpy as np

In [2]:
x = [1,2,3,3,5]

In [3]:
type(x)
type(np.array(x))

numpy.ndarray

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [18]:
a.ndim

2

In [9]:
c = a[(a>2)&(a>3)]
len(c)

5

In [5]:
z = np.array([[1,2],[3,4]])

In [6]:
z.ndim

2

In [7]:
np.array([1,2,3,4],ndmin=5)

array([[[[[1, 2, 3, 4]]]]])

In [8]:
np.array([1,2,3,4],dtype=float,ndmin=5)

array([[[[[1., 2., 3., 4.]]]]])

In [9]:
 np.array([1,2,3,4,"teeba"])

array(['1', '2', '3', '4', 'teeba'], dtype='<U11')

In [10]:
np.array([1,2,3,4,5,6.])

array([1., 2., 3., 4., 5., 6.])

In [11]:
x = np.array([[1,2,3],[4,5,6]])   #here two square bracket its two dimension
x.shape
x.ndim

2

In [12]:
y = np.array([[[1,2,3],[5,6,7]],[[1,2,3],[4,5,6]]])

In [13]:
print(y.shape)  #it gives 2 rows 3 columns and 2 array
print(y)

(2, 2, 3)
[[[1 2 3]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
np.array([[1,2,3],[4,5,6]],ndmin=5)

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

In [15]:
np.array([[1,2,3,4,5,6]],ndmin=5,dtype=float)  #give dtype for upcasting

array([[[[[1., 2., 3., 4., 5., 6.]]]]])

In [16]:
np.array([(1,3,4),(5,6,7)]) #we can give tuple forat data also so its not affected

array([[1, 3, 4],
       [5, 6, 7]])

In [17]:
#here we can change dtype for single single value 
# in first case a=1 so we upcast a into <i4 meand int32 and b=2 we upcast into <i8 int 64 like that fir next 
#tuple also work as same as previous
arr = np.array([(1,2),(4,5)],dtype=[("a","<i4"),("b","<i8")])

In [18]:
type(arr[0][0])

numpy.int32

In [19]:
type(arr[0][1])

numpy.int64

In [20]:
arr = np.array([[1,2],[3,4]])

In [21]:
arr

array([[1, 2],
       [3, 4]])

In [22]:
# we want to fatch 4
arr[1][1]

4

In [23]:
 mat = np.mat([[1,2],[3,4]])   #here we can get matrix  

In [24]:
np.asarray([1,2,3,4,5,6]) #we want to convert list into array

array([1, 2, 3, 4, 5, 6])

In [25]:
np.asanyarray([1,2,3,4,5,6]) #we want to convert list into array

array([1, 2, 3, 4, 5, 6])

In [26]:
# here we can not convert matrix into array becz matrix is suset of array
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [27]:
# here we can convert matrix into array 
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [28]:
issubclass(np.matrix,np.ndarray)

True

In [29]:
#array is a parent class and matrix is subclass
issubclass(np.ndarray,np.matrix)

False

In [30]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [31]:
c = a  #its known as a shallow copy

In [32]:
b  = a.copy()  #it is deep copy
#or
b = np.copy(a)

In [33]:
b[0][0] = 15

In [34]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
for i in b:
    print(i)

[15  2  3  4]
[5 6 7 8]


In [36]:
 np.fromfunction(lambda i,j:i==j,(5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [37]:
 np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [38]:
 #it gives a warning becz 1/0 is infinity but numpy is handeled
 np.fromfunction(lambda i,j:i/j,(3,3),dtype=int)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [39]:
[i*i for i in range(5)]
    

[0, 1, 4, 9, 16]

In [40]:
gen = (i*i for i in range(5))

In [41]:
for i in gen:
    print(i)

0
1
4
9
16


In [42]:
def test(x):
    yield x

In [43]:
for i in test(5):
    print(i)

5


In [44]:
gen = (i*i for i in range(5))

In [45]:
np.fromiter(gen,dtype=int)  #fromiter we can generate number

array([ 0,  1,  4,  9, 16])

In [46]:
np.fromiter(range(10),dtype=int)   #when we have gnerator type value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
#defaultly it converts into float
np.fromstring('12,3,4,5,6', sep=",", dtype=int)

array([12,  3,  4,  5,  6])

In [48]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

In [184]:
print(a[0])

[1 2 3 4]


In [50]:
a.T  #by this we can transpose rows and columns

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

In [51]:
print(a.ndim) #gives dimension  
print(a.size)  #gives total size
print(a.shape)  #gives shape row and column 

2
12
(3, 4)


In [52]:
a1 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [53]:
print(a1)

[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]


In [54]:
a1.shape # 2 number of 2 cross 4 dimension data

(2, 2, 4)

In [55]:
a1 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [56]:
a1.shape  #in 1 array we have 4 array with 2 croos 4 dimension

(1, 4, 2, 4)

In [57]:
list(range(10)) #range always take integer value

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
np.arange(6.6) #arange inside numpy it work as a range function 

array([0., 1., 2., 3., 4., 5., 6.])

In [59]:
np.arange(6.6,15,.3)

array([ 6.6,  6.9,  7.2,  7.5,  7.8,  8.1,  8.4,  8.7,  9. ,  9.3,  9.6,
        9.9, 10.2, 10.5, 10.8, 11.1, 11.4, 11.7, 12. , 12.3, 12.6, 12.9,
       13.2, 13.5, 13.8, 14.1, 14.4, 14.7, 15. ])

In [60]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [61]:
#included upper bound
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [62]:
#not included
np.linspace(1,4,4,endpoint=False,axis=0,dtype=int)

array([1, 1, 2, 3])

In [63]:
np.zeros((2,5,4))  #5 cross 4 data in two arrays

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [96]:
np.arange(5,9,2,dtype=int)

array([5, 7])

In [99]:
np.linspace(2,10,5,endpoint=False,dtype=int)

array([2, 3, 5, 6, 8])

In [109]:
np.logspace(2,5,20)   #it gives 20 values between 2 to 5 numbers

array([   100.        ,    143.84498883,    206.91380811,    297.63514416,
          428.13323987,    615.84821107,    885.86679041,   1274.2749857 ,
         1832.98071083,   2636.65089873,   3792.69019073,   5455.59478117,
         7847.59970351,  11288.37891685,  16237.76739189,  23357.2146909 ,
        33598.18286284,  48329.30238572,  69519.27961776, 100000.        ])

In [91]:
np.linspace(1,4,4,dtype=int)

array([1, 2, 3, 4])

In [64]:
np.ones((3,5,4),dtype=int)+6

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [65]:
np.eye(3,dtype=int)
#identtiy matrix is a square matrix
#diagonal elements equal to one

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [67]:
np.ones((2,3,5),dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [78]:
d = np.linspace(4,7,40)

In [79]:
d.ndim

1

In [80]:
d.shape

(40,)

In [85]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [87]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [88]:
d.reshape(2,1,20)  #give two array in 1-column 20-rows

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [110]:
np.random.rand(3)  #it gives all value b/w 0 and 1 follow a uniformal distribution 

array([0.93215975, 0.53891751, 0.28669347])

In [155]:
x = np.random.randn(5) #it gives us standard normal distribution

In [156]:
t = [0.93215975, 0.53891751, 0.28669347]
mean(t)
mean(x)

-1.0837424488210934

In [153]:
from statistics import mean
y = [1,2,3,4,5]
mean(y)

3

In [114]:
np.random.randn(2,3)

array([[-1.96832244,  0.01136375,  0.72483869],
       [-0.31792223, -0.57448757, -0.33896144]])

In [121]:
np.random.randint(5,60) #i genrate random integer between the range 

41

In [122]:
 np.random.randint(5,60,(5,5))  #we can generate 5 cross 5 array 

array([[51, 13, 15,  9,  5],
       [42, 52,  5, 31, 13],
       [11, 24, 57, 14,  9],
       [17, 35, 52, 27, 38],
       [35, 46, 47, 56, 11]])

In [127]:
arr = np.random.randint(3,9,(5,3))

In [128]:
arr

array([[8, 8, 8],
       [3, 6, 5],
       [4, 8, 3],
       [4, 7, 5],
       [6, 4, 6]])

In [131]:
arr.reshape(1,15)
arr.reshape(15,1)  #we can reshape the data 

array([[8],
       [8],
       [8],
       [3],
       [6],
       [5],
       [4],
       [8],
       [3],
       [4],
       [7],
       [5],
       [6],
       [4],
       [6]])

In [136]:
arr.reshape(1,1,15)

array([[[8, 8, 8, 3, 6, 5, 4, 8, 3, 4, 7, 5, 6, 4, 6]]])

In [139]:
arr.reshape(3,-1)

array([[8, 8, 8, 3, 6],
       [5, 4, 8, 3, 4],
       [7, 5, 6, 4, 6]])

In [142]:
arr.reshape(3,-1)

array([[8, 8, 8, 3, 6],
       [5, 4, 8, 3, 4],
       [7, 5, 6, 4, 6]])

In [157]:
arr.max()

8

In [158]:
arr.min()

3

In [164]:
arr1 = np.random.randint(5,30, (5,5))


In [167]:
print(arr1)

[[ 6  6 13  7 27]
 [12 25 12 13 25]
 [16 10 21 27  8]
 [ 6 25  7 16 29]
 [25 24  6 20 24]]


In [166]:
arr1[:,[1,3]] #all rows and column 1 and 3

array([[ 6,  7],
       [25, 13],
       [10, 27],
       [25, 16],
       [24, 20]])

In [168]:
arr1[:,1]  #all rows oand only one column

array([ 6, 25, 10, 25, 24])

In [173]:
arr1[arr1>10]

array([13, 27, 12, 25, 12, 13, 25, 16, 21, 27, 25, 16, 29, 25, 24, 20, 24])

In [174]:
arr1>10  #gives greater than 10

array([[False, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True, False],
       [False,  True, False,  True,  True],
       [ True,  True, False,  True,  True]])

In [175]:
arr2 = np.random.randint(1,10,(3,3))
arr3 = np.random.randint(2,6,(3,3))

In [178]:
print(arr2)
print(arr3)

[[7 5 6]
 [7 8 4]
 [2 4 1]]
[[2 3 2]
 [2 4 4]
 [5 3 5]]


In [ ]:
arr4 = arr2*arr3   #multiply with elements

In [177]:
arr4

array([[14, 15, 12],
       [14, 32, 16],
       [10, 12,  5]])

In [179]:
#if we have different different dimension array
# like one array 3 cross 2 and one array is 3 cross 3 
#at the last we will get after matrix multiplication  we get 3 cross 2 matrix
#matrix and array is same thing
arr5 = arr2@arr3  #matrix multiplication first row all column
print(arr5)

[[54 59 64]
 [50 65 66]
 [17 25 25]]


In [180]:
arr1**2

array([[ 36,  36, 169,  49, 729],
       [144, 625, 144, 169, 625],
       [256, 100, 441, 729,  64],
       [ 36, 625,  49, 256, 841],
       [625, 576,  36, 400, 576]], dtype=int32)

In [181]:
arr1

array([[ 6,  6, 13,  7, 27],
       [12, 25, 12, 13, 25],
       [16, 10, 21, 27,  8],
       [ 6, 25,  7, 16, 29],
       [25, 24,  6, 20, 24]])

In [182]:
np.sqrt(arr1)

array([[2.44948974, 2.44948974, 3.60555128, 2.64575131, 5.19615242],
       [3.46410162, 5.        , 3.46410162, 3.60555128, 5.        ],
       [4.        , 3.16227766, 4.58257569, 5.19615242, 2.82842712],
       [2.44948974, 5.        , 2.64575131, 4.        , 5.38516481],
       [5.        , 4.89897949, 2.44948974, 4.47213595, 4.89897949]])

In [183]:
np.log10(arr1)

array([[0.77815125, 0.77815125, 1.11394335, 0.84509804, 1.43136376],
       [1.07918125, 1.39794001, 1.07918125, 1.11394335, 1.39794001],
       [1.20411998, 1.        , 1.32221929, 1.43136376, 0.90308999],
       [0.77815125, 1.39794001, 0.84509804, 1.20411998, 1.462398  ],
       [1.39794001, 1.38021124, 0.77815125, 1.30103   , 1.38021124]])