# ARRAY
Array is a container which can hold a fix number of items and these items should be of the same data type. Most of the data structures make use of arrays to implement their algorithms. Following are the important terms to understand the concept of Array.

Element− Each item stored in an array is called an element.
Index − Each location of an element in an array has a numerical index, which is used to identify the element.

Following are the basic operations supported by an array.
Traverse − print all the array elements one by one.
Insertion − Adds an element at the given index.
Deletion − Deletes an element at the given index.
Search − Searches an element using the given index or by the value.
Update − Updates an element at the given index.

# NUMPY
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array
Numeric, the ancestor of NumPy, was developed by Jim Hugunin. Another package Numarray was also developed, having some additional functionalities. In 2005, Travis Oliphant created NumPy package by incorporating the features of Numarray into Numeric package. There are many contributors to this open source project.
OR/
NumPy, short for Numerical Python, is one of the most important foundational pack‐
ages for numerical computing in Python. Most computational packages providing
scientific functionality use NumPy’s array objects as the lingua franca(as like a bridge/interpreter)for data exchange.NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

NumPy contains, among other things:
A fast and efficient multidimensional array object ndarray Linear algebra operations, Fourier transform, and random number generation
Functions for performing element-wise computations with arrays or mathematical operations between arrays
. ndarray, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
• Mathematical functions for fast operations on entire arrays of data without having to write loops.
• Tools for reading/writing array data to disk and working with memory-mapped files.
• Linear algebra, random number generation, and Fourier transform capabilities

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. There are a number of reasons for this:
• NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences.
• NumPy operations perform complex computations on entire arrays without the need for Python for loops.

Beyond the fast array-processing capabilities that NumPy adds to Python, one of its primary uses in data analysis is as a container for data to be passed between algorithms and libraries.because many libraries we use for scientific computations and their algorithms we can not use direct on the given data sor for that we use array type of container always.

In [3]:
import numpy as np

In [4]:
x = [1,2,3,4,5,6]
type(x)

list

In [5]:
type(np.array(x))

numpy.ndarray

In [6]:
#Nested sequences,like a list of equal-length lists, will be converted into a multidimensional array:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
type(a)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [15]:
#for chcking dimension
print(a.ndim)
print(a.shape)

2
(2, 3)


In [11]:
#(no.rows,no.columns)
a.shape 

(2, 3)

In [8]:
#access data 
a[0]

array([1, 2, 3])

In [9]:
a[0][0]

1

In [10]:
x = [3,4,5,6,7.0]
print(np.array(x))  #upcasting here 

[3. 4. 5. 6. 7.]


In [18]:
#we can change dimensional
np.array([4,5,6,7],ndmin = 7)

array([[[[[[[4, 5, 6, 7]]]]]]])

In [20]:
#given tuples
np.array([(3,4),(5,6)],dtype = str)

array([['3', '4'],
       ['5', '6']], dtype='<U1')

In [22]:
#matrix is a subclass of array or array is superclass of matrices
x = np.mat([1,2,3,4,5])
x

matrix([[1, 2, 3, 4, 5]])

In [23]:
type(x)

numpy.matrix

In [25]:
np.array(x)

array([[1, 2, 3, 4, 5]])

In [26]:
#asanyarray = if my dataset is avilable some form  of numpy array we cantconvert into array 
np.asanyarray([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [27]:
np.asanyarray(x) #not conevert bcz matrix is subclass of array

matrix([[1, 2, 3, 4, 5]])

In [ ]:
#deep copy and sollow copy

In [28]:
a = np.array([4,5,6,7,8,9])

In [29]:
#this is not a good approach we saw in pandas code file
#solllow copy
b = a

In [30]:
b

array([4, 5, 6, 7, 8, 9])

In [31]:
#if we change in b so automatically change in a bcz both refering same location thats we use copy()
b[0]=505

In [33]:
a

array([505,   5,   6,   7,   8,   9])

In [38]:
a = np.array([4,5,6,7,8,9])

In [39]:
#deep copy
c = a.copy()

In [40]:
c

array([4, 5, 6, 7, 8, 9])

In [41]:
#this chnges only in c array not change in a array
c[0] = 404

In [42]:
c

array([404,   5,   6,   7,   8,   9])

In [43]:
a

array([4, 5, 6, 7, 8, 9])

In [45]:
#fromfunction:generate array based on internal given function
#match column and rows value
np.fromfunction(lambda x,y:x==y,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [47]:
np.fromfunction(lambda x,y:x+y,(4,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

In [49]:
A = np.fromfunction(lambda x,y:(x+y)*6,(4,3))

In [65]:
A.ndim
A

array([[ 0.,  6., 12.],
       [ 6., 12., 18.],
       [12., 18., 24.],
       [18., 24., 30.]])

In [67]:
A.shape
A.size
A.dtype

dtype('float64')

In [70]:
#arange function 
np.arange(5.3,10.5)

array([ 5.3,  6.3,  7.3,  8.3,  9.3, 10.3])

In [71]:
np.arange(5.3,10.5,2)

array([5.3, 7.3, 9.3])

In [72]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [73]:
#linspace function genreate numbers between start to stop 
np.linspace(3,7,20)  #including upper bound

array([3.        , 3.21052632, 3.42105263, 3.63157895, 3.84210526,
       4.05263158, 4.26315789, 4.47368421, 4.68421053, 4.89473684,
       5.10526316, 5.31578947, 5.52631579, 5.73684211, 5.94736842,
       6.15789474, 6.36842105, 6.57894737, 6.78947368, 7.        ])

In [76]:
np.linspace(50,100) #defalut 50 number gives

np.linspace(50,100,endpoint=False)
np.linspace(50,100,endpoint=False,retstep = True)


(array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62.,
        63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75.,
        76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88.,
        89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]),
 1.0)

In [77]:
#zeros function
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [80]:
z = np.zeros((2,5,6)) #here first element 2 is number of arrays
z

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [84]:
z.shape

(2, 5, 6)

In [87]:
z.size

60

In [90]:
#give any type of values
np.empty((2,2))

array([[1.69120416e-306, 1.78022342e-306],
       [6.23058028e-307, 1.06811422e-306]])

In [100]:
#identity matrix always square matrix(no.row==no.col)
x = np.eye(4)

In [101]:
y = np.eye(4)

In [102]:
z = x*y
z

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
#logspace function same as linespace only diff its gives log values
#give logvalues
np.logspace(5.6,7.6,5)

array([  398107.1705535 ,  1258925.41179417,  3981071.70553497,
       12589254.11794166, 39810717.05534969])

In [105]:
#random.rand (gives random numbers)
#gives uniformal distn take value 0 and 1
m = np.random.rand(4,5)

In [107]:
#reshaping m array alwys multiplication equal to(no.row*no.col)
m.reshape(5,4)

array([[0.31959052, 0.7717605 , 0.65853861, 0.59872951],
       [0.70528671, 0.36980091, 0.49618542, 0.29529737],
       [0.05834121, 0.23499464, 0.27971484, 0.81775591],
       [0.98239756, 0.58719399, 0.77174123, 0.7544432 ],
       [0.38832317, 0.67732282, 0.47382856, 0.85246313]])

In [108]:
m.reshape(10,2)  

array([[0.31959052, 0.7717605 ],
       [0.65853861, 0.59872951],
       [0.70528671, 0.36980091],
       [0.49618542, 0.29529737],
       [0.05834121, 0.23499464],
       [0.27971484, 0.81775591],
       [0.98239756, 0.58719399],
       [0.77174123, 0.7544432 ],
       [0.38832317, 0.67732282],
       [0.47382856, 0.85246313]])

In [113]:
#rand.randn fucntion(gives standard normal distributio values)
#mu=0,sigma=1 
np.random.randn(4,5)


array([[-0.12580166, -1.57202713, -0.84314375,  0.32592219,  1.17979767],
       [-1.50005035,  0.49226122,  0.4003651 , -0.29052621, -0.92139681],
       [-0.862205  ,  1.40875544,  0.31140204, -1.19961739,  0.25085153],
       [ 1.87569224, -0.45448193, -0.99353801, -0.43296818,  0.71021317]])

In [121]:
#random.randint
a = np.random.randint(3,8,(4,5))
a

array([[4, 3, 4, 3, 4],
       [4, 7, 5, 4, 7],
       [7, 7, 4, 7, 7],
       [7, 5, 3, 6, 7]])

In [122]:
a[0][0]

4

In [124]:
a[0:2] #exclude upper limit

array([[4, 3, 4, 3, 4],
       [4, 7, 5, 4, 7]])

In [126]:
a>3

array([[ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True]])

In [127]:
a[a>3]

array([4, 4, 4, 4, 7, 5, 4, 7, 7, 7, 4, 7, 7, 7, 5, 6, 7])

In [130]:
a[0][0] = 997

In [131]:
a

array([[997,   3,   4,   3,   4],
       [  4,   7,   5,   4,   7],
       [  7,   7,   4,   7,   7],
       [  7,   5,   3,   6,   7]])

In [133]:
m = np.array([[4,5,6],[3,2,1]])
m

array([[4, 5, 6],
       [3, 2, 1]])

In [134]:
n = np.array([[5,3,2],[2,1,4]])
n

array([[5, 3, 2],
       [2, 1, 4]])

In [135]:
#dimensional alwyas equal both arrays
m+n

array([[9, 8, 8],
       [5, 3, 5]])

In [136]:
#its not given actual matrix multiplication its gives only index multiplication 
m*n

array([[20, 15, 12],
       [ 6,  2,  4]])

In [137]:
# '@' this symbol use for matrix multiplication
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[2,5],[5,6]])

In [138]:
m1@m2

array([[12, 17],
       [26, 39]])

In [139]:
#power function
pow(m1,2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [141]:
m = np.zeros((3,4))

In [142]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
m+2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [147]:
n = np.array([1,2,3,4])

In [148]:
#this done by horizontal way 
m+n

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [149]:
#broadcasting -symiliaroperaation
#here we want to do in vertical format 
#using transpose (.T) transpose data row to column ,column to row
n1 = np.array([[3,4,5]]).T
n1

array([[3],
       [4],
       [5]])

In [150]:
m+n1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [153]:
m1 = np.random.rand(4,5).reshape(10,2)
m1

array([[0.27827591, 0.5607073 ],
       [0.68567437, 0.07857937],
       [0.98738659, 0.67192922],
       [0.20546018, 0.26346193],
       [0.40641716, 0.00483007],
       [0.74205655, 0.36487374],
       [0.24738993, 0.48874449],
       [0.46566809, 0.39540069],
       [0.75136864, 0.07098743],
       [0.79431421, 0.6322023 ]])

In [154]:
#sqrt
np.sqrt(m1)

array([[0.52751863, 0.74880391],
       [0.82805457, 0.28032012],
       [0.99367328, 0.81971289],
       [0.45327715, 0.51328543],
       [0.63750856, 0.06949869],
       [0.86142705, 0.6040478 ],
       [0.49738308, 0.69910263],
       [0.68239877, 0.62880895],
       [0.86681523, 0.26643467],
       [0.89124307, 0.7951115 ]])

In [155]:
#exponenet 
np.exp(m1)

array([[1.32085058, 1.75191119],
       [1.98511009, 1.08174921],
       [2.68421036, 1.95801111],
       [1.22809008, 1.30142775],
       [1.50142876, 1.00484175],
       [2.10025036, 1.44033214],
       [1.28067839, 1.63026811],
       [1.59307815, 1.48497909],
       [2.1198994 , 1.07356773],
       [2.21292287, 1.88175019]])

In [156]:
np.log10(m1)

array([[-0.55552439, -0.25126379],
       [-0.16388208, -1.10469145],
       [-0.00551277, -0.17267647],
       [-0.68727234, -0.57928213],
       [-0.39102796, -2.31604679],
       [-0.12956299, -0.43785739],
       [-0.60661799, -0.31091813],
       [-0.33192352, -0.40296258],
       [-0.12414694, -1.14881853],
       [-0.10000767, -0.19914393]])

In [161]:
m2 = np.random.rand(3,4)
m3 = np.random.rand(3,4)

In [163]:
#fmod always gives remainder
np.fmod(m2,m3)

array([[0.52327907, 0.48321044, 0.46423975, 0.51452091],
       [0.2836542 , 0.02262567, 0.52861301, 0.24480114],
       [0.17768287, 0.00599865, 0.44221706, 0.12461956]])

In [164]:
m2 = np.random.rand(3,4)

In [165]:
m2.ndim

2

In [176]:
m2 = m2.reshape(3,2,2)

In [177]:
m2.ndim

3

Flatten
The tool flatten creates a copy of the input array flattened to one dimension.

In [1]:
import numpy as np
my_array = np.array([[1,2,3],
                        [4,5,6]])

In [3]:
my_array.shape

(2, 3)

In [4]:
my_array.flatten()

array([1, 2, 3, 4, 5, 6])

Transpose

We can generate the transposition of an array using the tool numpy.transpose.
It will not affect the original array, but it will create a new array.

In [5]:
my_array = np.array([[1,2,3],
                        [4,5,6]])

In [6]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#with the help of seed we can not get different diff value
np.random.seed(13)
np.random.randint(1,10,(3,3))

# floor
The tool floor returns the floor of the input element-wise

In [3]:
x = [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]
my_array = np.array(x)
print(np.floor(my_array))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


# ceil
The tool ceil returns the ceiling of the input element-wise.

In [4]:
x = [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]
my_array = np.array(x)
print(np.ceil(my_array))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


# rint
The rint tool rounds to the nearest integer of input element-wise.

In [5]:
x = [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]
my_array = np.array(x)
print(np.rint(my_array))

[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [ ]:
np.set_printoptions(legacy='1.13')    #for work as formatted view of print 
x = np.array(input().split(),dtype=float)
print(np.floor(x),np.ceil(x),np.rint(x),sep='\n')

# sum
The sum tool returns the sum of array elements over a given axis.

In [6]:
my_array = np.array([ [1, 2], [3, 4] ])

In [10]:
print(np.sum(my_array, axis = 0))  #rowvice sum        
print(np.sum(my_array, axis = 1))   #columnvice sum
print(np.sum(my_array, axis = None))  #total sum    
print(np.sum(my_array))  


#By default, the axis value is None. Therefore, it performs 
#a sum over all the dimensions of the input array.

[4 6]
[3 7]
10
10


# prod

The prod tool returns the product of array elements over a given axis.

In [11]:
my_array = np.array([ [1, 2], [3, 4] ])

In [12]:
print(np.prod(my_array, axis = 0))  #rowvice multiplication        
print(np.prod(my_array, axis = 1))   #columnvice multply
print(np.prod(my_array, axis = None))  #total multyply    
print(np.prod(my_array))  


#By default, the axis value is None. Therefore, it performs 
#a multyply over all the dimensions of the input array.

[3 8]
[ 2 12]
24
24
